/**
 * Prompt sandbox — run this BEFORE trusting the report UI.
 *
 * The main risk in this prototype is that the model produces generic slop given
 * synthetic data (PRD success criterion #2). This script generates fresh
 * datasets at chosen severities and runs the real prompt against them with no
 * database and no UI in the way, so the prompt can be iterated cheaply.
 *
 *   node try-prompt.js              # severities 2, 5, 9
 *   node try-prompt.js 3            # just severity 3
 *   node try-prompt.js 3 --print    # dump the prompt instead of calling the model
 *
 * With no API key set it exercises the offline analysis path, which is still
 * useful for checking that the data itself is interesting enough to write about.
 */
import { generateDataset } from "./generator.js";
import { buildUserPrompt, generateReport, runGuardrail, aiConfigured } from "./ai.js";

const args = process.argv.slice(2);
const printOnly = args.includes("--print");
const scores = args.filter((a) => !a.startsWith("--")).map(Number).filter((n) => n >= 1 && n <= 10);
const severities = scores.length ? scores : [2, 5, 9];

const line = (char = "─") => console.log(char.repeat(78));

for (const healthScore of severities) {
  const dataset = generateDataset({ healthScore, days: 30, hasPartner: true });

  const payload = {
    patient: {
      age: 34,
      health_score: healthScore,
      description:
        "Test case generated by try-prompt.js. Seen fortnightly; presenting concerns unspecified.",
    },
    partnerName: "Sam",
    points: dataset.points,
    moodLogs: dataset.patient.moodLogs,
    journals: dataset.patient.journals,
    partnerMoodLogs: dataset.partner.moodLogs,
    partnerJournals: dataset.partner.journals,
    compliance: dataset.compliance,
  };

  line("═");
  console.log(`HEALTH SCORE ${healthScore}  ·  partner rolled at ${dataset.partner.healthScore}  ·  compliance ${dataset.compliance.score}%`);
  line("═");

  if (printOnly) {
    console.log(buildUserPrompt(payload));
    continue;
  }

  const { report, model_used } = await generateReport(payload);
  const guardrail = runGuardrail(report);

  console.log(`model: ${model_used}`);
  console.log(`guardrail: ${guardrail.passed ? "PASS" : `FAIL → ${guardrail.matches.join(", ")}`}`);
  line();
  console.log("SUMMARY\n" + report.summary + "\n");

  console.log("INSIGHTS");
  for (const i of report.insights || []) console.log(` • ${i.title}\n   ${i.detail}`);
  console.log();

  console.log("SPIKES");
  for (const s of report.spikes || []) {
    console.log(` • ${s.date} (${s.metric}) ${s.description}`);
    if (s.journal_context) console.log(`   journal: ${s.journal_context.slice(0, 100)}…`);
  }
  console.log();

  console.log("ACTIONABLE");
  for (const a of report.actionable_insights || []) console.log(` • ${a.suggestion}\n   ${a.rationale}`);
  console.log();
}

if (!aiConfigured() && !printOnly) {
  line();
  console.log("No API key set (PERSIST_HEALTH_API_KEY / OPENAI_API_KEY) — the above came from the");
  console.log("offline analysis path. Set a key to test the real prompt.");
}
